### ISSUE TITLE
Date Facet counts are incorrect

### ISSUE THREAD

**Issue by jyve** [cultuurnet/culturefeed#34]
The facet count for inactive items is incorrect for some of the predefined dates. After clicking on them, the right count appears. 
Since the site with the issue is still under development, I can only show screenshots unfortunately.

![screen shot 2015-04-23 at 21 25 23](https://cloud.githubusercontent.com/assets/303717/7305601/776b1f24-e9ff-11e4-8149-9133fcd91739.png)
![screen shot 2015-04-23 at 21 25 01](https://cloud.githubusercontent.com/assets/303717/7305602/776b465c-e9ff-11e4-9443-21eb544150a6.png)

**Comment by svenhoutmeyers** [comment]
Hello Jan-Yves,

We will take a look today!

S

**Comment by svenhoutmeyers** [comment]
Jan-Yves,

This is a known issue (for internal devs CULTSAPI-154), thing is that when we group on events on our SOLR "Today" +/- is allright, but on the next items it's not ok (it only counts on the first facetitem). It works   like it should work using facetField=datetype.old, but that's a performance killer. Our usability team also advices to remove the counts, because after a selection all the counts are the same, and that makes sense, but not to the user. Other sites also removes the count they say. If you know a good example that use counts on datetype facets they are glad to know ;). But we think to remove the counts in culturefeed_bootstrap.

**Comment by jyve** [comment]
OK, the counts have been removed. Thanks for the quick reply!
